### ISSUE TITLE
igraph update

### ISSUE THREAD

**Issue by lvmengxi** [soulj/PhenomeExpress#1]
When I repeat the example, I got following error. It seems the igraph function updates. Can you please provide a new version of example code? Thanks!

Best,
Mengxi

> LeukResults=runPhenomeExpress(upgrade_graph(pax5.network),dt,Phenotypes,"Mouse")
> [1] "D:/RNAseq/5. Subnetwork analyss/PhenomeExpress-master"
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...
> This graph was created by an old(er) igraph version.
>   Call upgrade_graph() on it to use with the current igraph version
>   For now we convert it on the fly...

**Comment by soulj** [comment]
Hi Mengxi,
The source code and examples have been updated and should now work with the latest version of igraph.
